### ISSUE TITLE
When the floor price rises rapidly during the auction process, it will result in deny bid.

### ISSUE THREAD

**Issue by xiaoxiaoleo** [BendDAO/bend-protocol#44]
**Describe the bug**
When the floor price rises rapidly during the auction process, it will result in deny bid.
In LiquidateLogic.sol - executeAuction():
```
      // loan's accumulated debt must exceed threshold (heath factor below 1.0)
      require(vars.borrowAmount > vars.thresholdPrice, Errors.LP_BORROW_NOT_EXCEED_LIQUIDATION_THRESHOLD);

```
thresholdPrice will increase when floor price rise, if floor price rise is high enough to cause heath factor greater than 1.0, then customer can not bid anymore.  

 

**Screenshots**
![image](https://user-images.githubusercontent.com/9813186/171086697-b0c0fc9a-2dbc-4f8e-9ab2-9aedb00da219.png)

**Comment by thorseldon** [comment]
Look at the state check, only the first-time bid will check this.
The loan state will change to Auction after the first bid succeeds.
